# Generated by Django 4.1.7 on 2023-04-01 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='visit_duration',
            field=models.DurationField(verbose_name=datetime.timedelta(0)),
        ),
    ]
