# Generated by Django 4.1.7 on 2023-04-01 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0002_alter_schedule_visit_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='visit_duration',
            field=models.DurationField(),
        ),
    ]
