# Generated by Django 4.1.7 on 2023-04-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0003_alter_schedule_visit_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='visit_duration',
            new_name='delay',
        ),
    ]
