# Generated by Django 4.1.7 on 2023-04-01 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0004_rename_visit_duration_schedule_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='delay',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
