# Generated by Django 4.1.7 on 2023-04-01 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0005_alter_schedule_delay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='commande_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
