# Generated by Django 4.1.7 on 2023-04-01 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0007_remove_commande_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='segment',
        ),
    ]
