# Generated by Django 4.1.7 on 2023-04-01 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0008_remove_commande_devise_remove_commande_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='commande_date',
        ),
    ]
