# Generated by Django 4.1.7 on 2023-04-01 23:08

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0011_commande_devise_commande_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='pays',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
