# Generated by Django 4.1.7 on 2023-04-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0012_commande_pays'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='pays',
            new_name='country',
        ),
    ]
