# Generated by Django 4.1.7 on 2023-04-01 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0013_rename_pays_commande_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commande',
            old_name='country',
            new_name='pays',
        ),
    ]
