# Generated by Django 4.1.7 on 2023-04-02 16:44

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0015_remove_commande_pays'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='pays',
            field=django_countries.fields.CountryField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
