# Generated by Django 4.1.7 on 2023-04-02 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0017_remove_commande_pays'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='devise',
        ),
        migrations.RemoveField(
            model_name='commande',
            name='segment',
        ),
    ]
