# Generated by Django 4.1.7 on 2023-04-03 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0019_commande_devise_commande_pays_commande_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='reference',
        ),
    ]
