# Generated by Django 4.1.7 on 2023-04-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0020_remove_commande_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='reference',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
