# Generated by Django 4.1.7 on 2023-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0021_commande_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
