# Generated by Django 4.1.7 on 2023-05-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0022_alter_commande_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel1', models.CharField(blank=True, max_length=100)),
                ('tel2', models.CharField(blank=True, max_length=100)),
                ('mail', models.EmailField(default='buhofergnami@fastmail.fm', max_length=250)),
                ('image', models.ImageField(upload_to='static/img/')),
                ('image1', models.ImageField(upload_to='static/img/')),
                ('image2', models.ImageField(upload_to='static/img/')),
                ('whatsapp', models.CharField(blank=True, default='https://www.whatsapp.com/', max_length=255, null=True)),
                ('facebook', models.CharField(blank=True, default='https://www.facebook.com/', max_length=255, null=True)),
                ('instagram', models.CharField(blank=True, default='https://www.instagram.com/', max_length=255, null=True)),
                ('tiwer', models.CharField(blank=True, default='https://twitter.com/', max_length=255, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
