# Generated by Django 4.1.7 on 2023-05-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0025_rename_scrore_site_score_alter_accueil_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='diwe_product.package'),
        ),
        migrations.AlterField(
            model_name='image',
            name='route',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diwe_product.diweroute'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diwe_product.site'),
            preserve_default=False,
        ),
    ]
