# Generated by Django 4.1.7 on 2023-05-14 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0026_alter_image_package_alter_image_route_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='diwe_product.diwecategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='site',
            name='ville',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diwe_product.ville'),
            preserve_default=False,
        ),
    ]
