# Generated by Django 4.1.7 on 2023-05-14 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0027_alter_site_category_alter_site_name_alter_site_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='code_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='commande',
            name='numero_rue',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='commande',
            name='rue',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='commande',
            name='segment',
            field=models.CharField(choices=[('Adulte', 'Adulte'), ('Enfant', 'Enfant')], max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='tel1',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='commande',
            name='ville',
            field=models.CharField(max_length=50),
        ),
    ]
