# Generated by Django 4.1.7 on 2023-05-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diwe_product', '0030_remove_accueil_id_accueil__id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detailcommande',
            options={'verbose_name': 'Detail commande', 'verbose_name_plural': 'Detail commandes'},
        ),
        migrations.AlterModelOptions(
            name='diwecategory',
            options={'verbose_name': 'Categorie', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='diweregion',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='diweroute',
            options={'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Produit', 'verbose_name_plural': 'Produits'},
        ),
        migrations.RenameField(
            model_name='accueil',
            old_name='tiwer',
            new_name='twitter',
        ),
    ]
